name: Android CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'android/**'
      - '.github/workflows/android.yml'
    tags:
      - v*.*

 
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build
        
    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/') != true
      with:
        prerelease: true
        draft: false
        automatic_release_tag: continuous-android
        title: Continuous Builds (Android)
        files: |
          app/build/outputs/apk/debug/app-debug.apk 
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        prerelease: false
        draft: true
        files: |
          app/build/outputs/apk/debug/app-debug.apk 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
